# RBAC - Role allowing to list and get pods in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
# RBAC - RoleBinding linking the ServiceAccount to the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
