apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "postgres"
  DB_NAME: {{ .Values.infrastructure.postgres.db | quote }}
  RABBITMQ_HOST: "eglh-rabbitmq"
  RABBIT_PORT: "5672"
