apiVersion: v1
kind: ResourceQuota
metadata:
  name: logistics-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: {{ .Values.quota.pods | quote }}
    requests.cpu: {{ .Values.quota.requests.cpu | quote }}
    requests.memory: {{ .Values.quota.requests.memory | quote }}
    limits.cpu: {{ .Values.quota.limits.cpu | quote }}
    limits.memory: {{ .Values.quota.limits.memory | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: logistics-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
